### ISSUE TITLE
Cannot open faction spawn detection area

### ISSUE THREAD

**Issue by leone007** [Geuthur/EVE-Alert#15]
The app works miracles detecting neuts. I have 3 alts sitting in cloak, all the necessary windows are cropped and transfered to OBS, evealerts detection area is the projector window. So basically I can stream 3 locals (and gates) with local neut detection. Marvelous indeed!

However. My plan was to use faction detection to detect in/unactivated cloaking device (the reasons are obvious). So I made a custom wav (using old AURA voicelines) and took a screenshot (using snipping tool, in the OBS projector window, where detection should happen, so there should be no scaling issues) of the inactivated cloaking device icon, both named following the rules, but nothing happens. 

No message in evealert about faction detection, and I can't even open faction detection region. (I can open enemy detecion region).

Is it imperative that these regions have no matching parts? (right now, both detection areas are the same)

UPDATE: now I made sure that the two different detection regions have no overlapping areas, still no joy :(

**Comment by Geuthur** [comment]
Hey,

That you can't open the Window is interesting, i have tested it and it works for me.
![Screenshot 2024-11-20 142548](https://github.com/user-attachments/assets/539544fb-8e54-401d-a3f3-f01a8c823949)
![Screenshot 2024-11-20 143045](https://github.com/user-attachments/assets/cdfbaf33-32eb-4515-b6b5-fe6614b4c4bc)

Maybe there is something other wrong??
Can you show me the settings.json ?

The Problem actually is that, I not have made a Detectionrange for the Faction Spawn, Maybe I need to add this too

**Comment by leone007** [comment]
{
    "logging": "ERROR",
    "alert_region_1": {
        "x": "-1920",
        "y": "1001"
    },
    "alert_region_2": {
        "x": "-498",
        "y": "1900"
    },
    "faction_region_1": {
        "x": "-1920",
        "y": "940"
    },
    "faction_region_2": {
        "x": "-498",
        "y": "1000"
    },
    "detectionscale": {
        "value": 80.0
    },
    "detection_mode": {
        "value": "picture"
    },
    "cooldown_timer": {
        "value": "90"
    }
}

**Comment by leone007** [comment]
So you can open both betection windows at the same time?

**Comment by Geuthur** [comment]
I have noticed that if the detection is on going you can't open the vision window and some errors occurs i will look at this maybe this is the issue.

Yes you can Open both.

![Screenshot 2024-11-20 143855](https://github.com/user-attachments/assets/61796dc7-5cbb-4ebb-9ff5-3cca3c6b704d)

The Settings looks ok.
Normally if something is wrong you will get an settings wrong hint.

**Comment by leone007** [comment]
So basically you opened evemon, opened both regions and THEN started the script? If I try that, I cannot even open Enemy Vision. I have to start script first.

**Comment by Geuthur** [comment]
I think this is an Program side error i will look at it and solve it.

This not happen with the Enemy Detection so there must be something wrong on the Faction Detection

**Comment by Geuthur** [comment]
Should be fixed now.

**Comment by leone007** [comment]
Unfortunately it isn't :( 

I have replaced the main.exe with the new version (settings.json and images and sounds are the same as before), and the behavior is exactly the same. If I start the script, it gives an error message: _Something went wrong please set the Alert Region new_ and I still cannot open Faction Region, and faction detection doesn't work either.

**Comment by Geuthur** [comment]
Hey,

Does the whole Alert not work or only the Faction?
Cause this error says that the Region area is wrong you need to setting up as follows 

First point top left corner
Second point bottom right corner.

Otherwise you get the Wrong Alert Region error.

I have trat after the New Patch the script and the factiom regio  can be open every time if the Alert is started

**Comment by leone007** [comment]
Enemy Alert works flawlessly, and I can open Enemy Vision too. 

Should I set a new Faction Region? Right now this is settings.json

{
    "logging": "ERROR",
    "alert_region_1": {
        "x": "-1920",
        "y": "1001"
    },
    "alert_region_2": {
        "x": "-498",
        "y": "1900"
    },
    "faction_region_1": {
        "x": "-1920",
        "y": "920"
    },
    "faction_region_2": {
        "x": "-498",
        "y": "1000"
    },
    "detectionscale": {
        "value": 80.0
    },
    "detection_mode": {
        "value": "picture"
    },
    "cooldown_timer": {
        "value": "90"
    }
}

**Comment by Geuthur** [comment]
Yes try that and important Note if you setting top left corner you need to go right Direction on the Second point.

**Comment by leone007** [comment]
OK, But how do I set faction Region apart from using the coordinates in Settings window? 

<img width="488" alt="evealert detection regions" src="https://github.com/user-attachments/assets/e2f98ee8-3697-4f99-b161-4d971257d3af">

I have set Enemy Region this way and it worked.

**Comment by leone007** [comment]
No matter what coordinates I write into Settings for Facton Region , it gives the same error, _Something went wrong please set the Alert Region new_.

Confiig Mode sets the Enemy Region am I right? (Ohhh F2!)

**Comment by Geuthur** [comment]
https://github.com/user-attachments/assets/1c1fd8c5-73c1-4efe-9e91-4855c0198b0f

**Comment by leone007** [comment]
![image](https://github.com/user-attachments/assets/957a4732-6450-4e3c-8f01-a1aca4ba46e4)

**Comment by Geuthur** [comment]
I made a Video with Full Explanation of both Alarm Region and Faction Region

https://github.com/Geuthur/EVE-Alert-Opensource/issues/15#issuecomment-2503206740

**Comment by leone007** [comment]
OK, I'll try tor ecord what happens on my screen.

**Comment by leone007** [comment]
My OBS is in use, and I cannot record windows desktop with anything else, If I do exactly the same as you in that video, I get this:

![image](https://github.com/user-attachments/assets/c2344e60-801f-4acc-b744-69e31f5a3787)

**Comment by Geuthur** [comment]
can you show me the log file in logs

**Comment by leone007** [comment]
Where is the logs folder?

**Comment by leone007** [comment]
https://github.com/user-attachments/assets/187e3318-3efb-4860-8a36-440a77369617

**Comment by leone007** [comment]
The log file is 747 MB

**Comment by Geuthur** [comment]
ok delete it and then make the same process before and sent me then the log ^^..

**Comment by Geuthur** [comment]
i think the image is wrong thats the problem maybe

**Comment by leone007** [comment]
[alert.log](https://github.com/user-attachments/files/17931380/alert.log)
I deleted previous log, here is a new one.

**Comment by leone007** [comment]
I deleted previous log, here is a new one.

**Comment by Geuthur** [comment]
What ending has your image ?

can you send me the image that i can reproduce the problem to solve it

**Comment by leone007** [comment]
<img width="25" alt="faction_1" src="https://github.com/user-attachments/assets/2d734856-d086-450e-89f0-e6d9e4ce4c84">

**Comment by leone007** [comment]
<img width="52" alt="faction_1" src="https://github.com/user-attachments/assets/701c842d-2de6-44b8-b3d9-ede78f8028bb">

**Comment by leone007** [comment]
It does the same, no matter what image I use
[alert.log](https://github.com/user-attachments/files/17931642/alert.log)

**Comment by Geuthur** [comment]
kk can you tell me it is a jpg or png?

**Comment by leone007** [comment]
It is a .png made by windows snipping tool, from the window I use for detection (see 1st post on this issue)

**Comment by Geuthur** [comment]
this maybe not work you need to take the screenshot per the alert region think F3

**Comment by leone007** [comment]
The previous video was taken on my 4K main screen, this one was taken on my 1080p screen that I use for detection.:


https://github.com/user-attachments/assets/49bb180a-d7fe-42b2-bc9b-fc176c4e7aaa

**Comment by leone007** [comment]
Also, please notice, that if I put my cursor in the top left corner of my 1080p screen, the coordinates aren't right. -2880 to 0 on the X axis on a 1920 pixel width screen.


https://github.com/user-attachments/assets/28baade1-3343-4c97-91f2-0303a49589a3

Y axis goes from 1405 to 3034, that is 1629 pixels on a 1080 pixel high screen. So mouse position detection isn't working well either, somehow it calculates the position based relative to 4k screen?

Mouse detection sees the 1080p screen 1.5x bigger in both dimension.

**Comment by Geuthur** [comment]
Its difficult so solve atm.

The Code isn't good.
If I get time I will work on a completly new one in a better way it was one of my first projects.

**Comment by leone007** [comment]
That is OK, as you can see, if I set the coordinates manually in the Settings window, it detects the right area for Alert, the issue is only with Faction.

**Comment by Geuthur** [comment]
So i am not sure if i fix it but can you try maybe cause it works for me so i can't test it anymore.
![Screenshot 2024-11-27 135901](https://github.com/user-attachments/assets/f61259c9-2cfc-46b7-9924-e9b6a1a1ffd1)

I will let you know if there is a finish version of it at the moment i need to fix some issues with multiple monitors

You can Checkout the progress here
https://github.com/Geuthur/EVE-Alert-Opensource/tree/new-region-system

**Comment by Geuthur** [comment]
@leone007 

https://github.com/Geuthur/EVE-Alert-Opensource/releases/tag/v0.4.5a2

can you try this alpha version.

I am not sure this should fix all you stuff.
The Monitors problem should be fixed and the Faction Detection problem.

With F1 and F2 please to set the region.

Let me know when something not work.

**Comment by leone007** [comment]
I couldn't start it, it gives a python error message, and quits. 
![image](https://github.com/user-attachments/assets/df1f2e5b-da2d-4323-ac23-0b267d70f795)

**Comment by Geuthur** [comment]
@leone007 

https://github.com/Geuthur/EVE-Alert-Opensource/releases/tag/v0.4.5a3

This should work now i forgot to add it to the requirments.txt

With this version all your problems should be fixed.
I found the issues with Snipping Tool and also have add a Seperate Detection Scale for the Faction Detection

NOTE: This is not a final version
